[package]
name = "naz"
version = "0.1.0"
authors = ["Derek Crosson <derekcrosson18@gmil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
